version: '3'

services:
  node-app:
    build:
      context: ./app
    container_name: node-app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s sh -c "npm install && node app.js"
    restart: always
    volumes:
      - ./app:/usr/src/app
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: nodedb
    networks:
      - node-network
    tty: true
    depends_on:
      - db

  db:
    build:
      context: ./db
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes: 
      - ./db/mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - TZ=America/Sao_Paulo
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - node-network
    depends_on:
      - node-app

networks:
  node-network:
    driver: bridge